### PR TITLE
Design folder updates

### PR DESCRIPTION
**Pull request by VictoriaODell**
I want to make it more detailed later but lmk if this works for now @mateoclarke 

....Also I just noticed that css stuff. I don't think I did that. Idk what I did. 🙃

### CODE REVIEW

**Comment by mateoclarke** [comment]
@VictoriaODell: I did notice that the Google Drive folder you link from in the README is empty. 
https://drive.google.com/drive/folders/0BwKb2oghmQldTEZ2V3U4OGxHZWM

**Comment by mateoclarke** [comment]
@VictoriaODell: Also a note about the naming our versions in order to be consistent.

We are actually calling the version from last year Version 0. (0.1.0)
And the Version that we launched with the new designs Version 1. (1.0.0)
Small changes we make without causing major breaking changes we'll call v1.1.0, v1.2.0, etc as we go forward.

Just pointing this out because it looks like we are calling the old design assets in the Google Drive Version 1.0 and the new stuff 1.1.

There's a whole philosophy around this called semantic versioning. And we could've started at 1.0.0. But it also is common to start at 0.1.0 when you're just building a test and then working you're way up to version 1.0.0.
 
> Given a version number MAJOR.MINOR.PATCH, increment the:

> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

**Comment by VictoriaODell** [comment]
@mateoclarke yeah. I made that as a placeholder. I just placed a file in there. The files got off at some point so I need to merge some sketch files to really reflect the latest.

**Comment by VictoriaODell** [comment]
@mateoclarke okay, I'll rename. I think I just got confused. 😛

**Pull request merged**
